[General]
Name = OaKhz Audio
Class = 0x400428
Discoverable = true
DiscoverableTimeout = 0
PairableTimeout = 0
JustWorksRepairing = always
FastConnectable = true

[Policy]
AutoEnable = true
ReconnectUUIDs = 0000110d-0000-1000-8000-00805f9b34fb,0000110e-0000-1000-8000-00805f9b34fb
